---
title: "Blog 1 Data"
author: "Feven Yohannes"
date: "September 11, 2020"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(readr)
library(tidyr)
library(ggplot2)
library(dplyr)
library(maps)
library(cowplot)
library(ggrepel)

# For the labeling of my map graph

library(tidyverse)

```

```{r, Downloading data}

 # Reading in data 1

popvote_bystander <- read_csv("popvote_bystate_1948-2016.csv",col_types = cols(
  state = col_character(),
  year = col_double(),
  total = col_double(),
  D = col_double(),
  R = col_double(),
  R_pv2p = col_double(),
  D_pv2p = col_double()
))

 # Reading in data 2

popvote <- read_csv("popvote_1948-2016.csv",col_types = cols(
  year = col_double(),
  party = col_character(),
  winner = col_logical(),
  candidate = col_character(),
  pv = col_double(),
  pv2p = col_double(),
  incumbent = col_logical(),
  incumbent_party = col_logical(),
  prev_admin = col_logical()
))
```

```{r, Graph 1}

# Making the dataframe wider

popvote_wide_df <- popvote %>%
  select(year, party, pv2p) %>%
  spread(party, pv2p)


  # Creating graph 1 dataframe

graph1_df <- popvote_wide_df %>%
  
  # Create new variable to look at vote share difference
  
  mutate(difference = (democrat-republican),absolute_difference =abs(democrat-republican)) %>%

  
  # Mutate to get colors for graph
  
  mutate(Color = ifelse(difference > 0, "blue", "red")) %>%
  
  # Making sure there are no duplicates, while keeping all other variables
  
  distinct(year, .keep_all = TRUE) %>%
  mutate(avg=mean(absolute_difference))
  
  
  # Creating Graph 1

  graph1_df %>%
  ggplot(aes(x=year,y=absolute_difference,fill=Color)) +geom_col() +
  labs(title ="Difference in National Popular Vote in Presidential Elections from 1948 to 2016",
        subtitle="Exploring Win Margins by Democrats and Republicans",
    x="Election Year",y= "Difference in Popular Vote (%)",
    caption= "Source: Presidential Popular Vote Average 1948-2016 Dataset") +
  theme(plot.title = element_text(face = "bold",size=30))+
  theme(plot.subtitle = element_text(face = "bold",size=29)) +
  theme(plot.caption =element_text(face = "bold",size=27))+
    scale_fill_manual(labels=c("Democrat", "Republican"), values = c("blue", "red")) +
    labs(fill = "Party that Won the Popular Vote") +
    theme(axis.title.x = element_text(size = 30),
          axis.title.y = element_text(size = 30)) +
    theme(
  legend.title = element_text(color = "black", size = 29),
  legend.text = element_text(color = "black", size = 29)
  ) +
    theme(axis.text.x = element_text(color = "black", size = 26, hjust = .5, vjust = .5, face = "plain"),
        axis.text.y = element_text(color = "black", size = 26, angle = 0, hjust = 1, vjust = 0, face = "plain")) 
  
  
  ggsave("PV_historical.png", height = 13, width = 21)

```



```{r,Graphic 2}

Texas <- popvote_bystander %>%
  filter(state=="Texas")


 # Arizona 

Arizona <- popvote_bystander %>%
  filter(state=="Arizona") %>%
  filter(year>1980) %>%
  
  # Tidying Data- prep for graph 
  
  gather(key = party,value = party_share,D_pv2p,R_pv2p) %>%
  
  # Creating ggplot
  
  ggplot(aes(x=year,y=party_share,fill=party)) +geom_col() +
  labs(title ="Arizona's Presidential Vote Share",
       subtitle = "1980-2016",
    x="Election Year",y= "Vote Share(%)") +
  theme(axis.title.y = element_text(size=1)) +
  theme(plot.title = element_text(face = "bold",size=26)) +
    scale_fill_manual(labels=c("Democrat", "Republican"), values = c("blue", "red")) +
    labs(fill = "Party") +
  theme(legend.title = element_text(color = "gray1", size = 28),legend.key.width = unit(0.8,"cm"),legend.key.size = unit(0.8, "cm")) +
    theme(
  legend.text = element_text(color = "black", size = 22)
  ) +
  theme(
  axis.title.x = element_text(size = 28),
  axis.title.y = element_text(size = 28)) +
    theme(axis.text.x = element_text(color = "black", size = 28, hjust = .5, vjust = .5, face = "plain"),
        axis.text.y = element_text(color = "black", size = 28, angle = 0, hjust = 1, vjust = 0, face = "plain"))+
  theme(plot.subtitle = element_text(face = "bold",size=26))

# Florida

Florida <- popvote_bystander %>%
  filter(state=="Florida") %>%
  filter(year>1980) %>%
  
  # Tidying Data- prep for graph 
  
  gather(key = party,value = party_share,D_pv2p,R_pv2p) %>%
  
  # Creating ggplot
  
  ggplot(aes(x=year,y=party_share,fill=party)) +geom_col() +
  labs(title ="Florida's Presidential Popular Vote Share",
       subtitle = "1980-2016",
    x="Election Year",y= "Vote Share(%)") +
  theme(plot.title = element_text(face = "bold",size=26)) +
    scale_fill_manual(labels=c("Democrat", "Republican"), values = c("blue", "red")) +
    labs(fill = "Party") +
  theme(legend.title = element_text(color = "gray1", size = 20),legend.key.width = unit(0.8,"cm"),legend.key.size = unit(0.8, "cm")) +
    theme(
  legend.text = element_text(color = "black", size = 22)
  )+
    theme(axis.text.x = element_text(color = "black", size = 28, hjust = .5, vjust = .5, face = "plain"),
        axis.text.y = element_text(color = "black", size = 28, angle = 0, hjust = 1, vjust = 0, face = "plain"))+
  theme(
  axis.title.x = element_text(size = 28),
  axis.title.y = element_text(size = 28))+
  theme(plot.subtitle = element_text(face = "bold",size=24))


# Georgia 

Georgia <- popvote_bystander %>%
  filter(state=="Georgia") %>%
  filter(year>1980) %>%
  
  # Tidying Data- prep for graph 
  
  gather(key = party,value = party_share,D_pv2p,R_pv2p) %>%
  
  # Creating ggplot
  
  ggplot(aes(x=year,y=party_share,fill=party)) +geom_col() +
  labs(title ="Georgia's Presidential Popular Vote Share",
       subtitle = "1980-2016",
    x="Election Year",y= "Vote Share(%)") +
  theme(plot.title = element_text(face = "bold",size=27))+
    scale_fill_manual(labels=c("Democrat", "Republican"), values = c("blue", "red")) +
    labs(fill = "Party") +
  theme(legend.title = element_text(color = "gray1", size = 22),legend.key.width = unit(0.8,"cm"),legend.key.size = unit(0.8, "cm")) +
    theme(
  legend.text = element_text(color = "black", size = 22)
  )+
    theme(axis.text.x = element_text(color = "black", size = 28, hjust = .5, vjust = .5, face = "plain"),
        axis.text.y = element_text(color = "black", size = 28, angle = 0, hjust = 1, vjust = 0, face = "plain"))+
  theme(
  axis.title.x = element_text(size = 28),
  axis.title.y = element_text(size = 28))+
  theme(plot.subtitle = element_text(face = "bold",size=24))

  # Michigan 

Michigan <- popvote_bystander %>%
  filter(state=="Michigan") %>%
  filter(year>1980) %>%
  
  # Tidying Data- prep for graph 
  
  gather(key = party,value = party_share,D_pv2p,R_pv2p) %>%
  
  # Creating ggplot
  
  ggplot(aes(x=year,y=party_share,fill=party)) +geom_col() +
  labs(title ="Michigan's Presidential Popular Vote Share",
       subtitle = "1980-2016",
    x="Election Year",y= "Vote Share(%)") +
  theme(plot.title = element_text(face = "bold",size=26)) +
    scale_fill_manual(labels=c("Democrat", "Republican"), values = c("blue", "red")) +
    labs(fill = "Party") +
  theme(legend.title = element_text(color = "gray1", size = 22),legend.key.width = unit(0.8,"cm"),legend.key.size = unit(0.8, "cm")) +
    theme(
  legend.text = element_text(color = "black", size = 19)
  )+
    theme(axis.text.x = element_text(color = "black", size = 29,hjust = .5, vjust = .5, face = "plain"),
        axis.text.y = element_text(color = "black", size = 28, angle = 0, hjust = 1, vjust = 0, face = "plain"))+
  theme(
  axis.title.x = element_text(size = 28),
  axis.title.y = element_text(size = 28))+
  theme(plot.subtitle = element_text(face = "bold",size=24))

  # Minnesota 

Minnesota <- popvote_bystander %>%
  filter(state=="Minnesota") %>%
  filter(year>1980) %>%
  
  # Tidying Data- prep for graph 
  
  gather(key = party,value = party_share,D_pv2p,R_pv2p) %>%
  
  # Creating ggplot
  
  ggplot(aes(x=year,y=party_share,fill=party)) +geom_col() +
  labs(title ="Minnnesota's Presidential Popular Vote Share",
       subtitle = "1980-2016",
    x="Election Year",y= "Vote Share(%)") +
  theme(plot.title = element_text(face = "bold",size=23)) +
    scale_fill_manual(labels=c("Democrat", "Republican"), values = c("blue", "red")) +
    labs(fill = "Party") +
  theme(legend.title = element_text(color = "gray1", size = 22),legend.key.width = unit(0.8,"cm"),legend.key.size = unit(0.8, "cm")) +
    theme(
  legend.text = element_text(color = "black", size = 17)
  )+
    theme(axis.text.x = element_text(color = "black", size = 27, hjust = .5, vjust = .5, face = "plain"),
        axis.text.y = element_text(color = "black", size = 27, angle = 0, hjust = 1, vjust = 0, face = "plain"))+
  theme(
  axis.title.x = element_text(size = 28),
  axis.title.y = element_text(size = 28))+
  theme(plot.subtitle = element_text(face = "bold",size=24))


  # North Carolina 

North_Carolina  <- popvote_bystander %>%
  filter(state=="North Carolina") %>%
  filter(year>1980) %>%
  
  # Tidying Data- prep for graph 
  
  gather(key = party,value = party_share,D_pv2p,R_pv2p) %>%
  
  # Creating ggplot
  
  ggplot(aes(x=year,y=party_share,fill=party)) +geom_col() +
  labs(title ="North Carolina's Presidential Popular Vote Share",
       subtitle = "1980-2016",
    x="Election Year",y= "Vote Share(%)") +
  theme(plot.title = element_text(face = "bold",size=21)) +
    scale_fill_manual(labels=c("Democrat", "Republican"), values = c("blue", "red")) +
    labs(fill = "Party") +
  theme(legend.title = element_text(color = "gray1", size = 22),legend.key.width = unit(0.8,"cm"),legend.key.size = unit(0.8, "cm")) +
    theme(
  legend.text = element_text(color = "black", size = 17)
  )+
    theme(axis.text.x = element_text(color = "black", size = 27, hjust = .5, vjust = .5, face = "plain"),
        axis.text.y = element_text(color = "black", size = 27, angle = 0, hjust = 1, vjust = 0, face = "plain"))+
  theme(
  axis.title.x = element_text(size = 28),
  axis.title.y = element_text(size = 28))+
  theme(plot.subtitle = element_text(face = "bold",size=21))


  #Pennsylvania 

Pennsylvania <- popvote_bystander %>%
  filter(state=="Pennsylvania") %>%
  filter(year>1980) %>%
  
  # Tidying Data- prep for graph 
  
  gather(key = party,value = party_share,D_pv2p,R_pv2p) %>%
  
  # Creating ggplot
  
  ggplot(aes(x=year,y=party_share,fill=party)) +geom_col() +
  labs(title ="Pennsylavnia's Presidental Vote Share",
       subtitle = "1980-2016",
    x="Election Year",y= "Vote Share(%)") +
  theme(plot.title = element_text(face = "bold",size=25)) +
    scale_fill_manual(labels=c("Democrat", "Republican"), values = c("blue", "red")) +
    labs(fill = "Party") +
  theme(legend.title = element_text(color = "gray1", size = 18),legend.key.width = unit(0.8,"cm"),legend.key.size = unit(0.8, "cm")) +
    theme(
  legend.text = element_text(color = "black", size = 17)
  )+
    theme(axis.text.x = element_text(color = "black", size = 27, hjust = .5, vjust = .5, face = "plain"),
        axis.text.y = element_text(color = "black", size = 27, angle = 0, hjust = 1, vjust = 0, face = "plain"))+
  theme(
  axis.title.x = element_text(size = 28),
  axis.title.y = element_text(size = 28))+
  theme(plot.subtitle = element_text(face = "bold",size=24))


  # Wisconsin 

Wisconsin <- popvote_bystander %>%
  filter(state=="Wisconsin") %>%
  filter(year>1980) %>%
  
  # Tidying Data- prep for graph 
  
  gather(key = party,value = party_share,D_pv2p,R_pv2p) %>%
  
  # Creating ggplot
  
  ggplot(aes(x=year,y=party_share,fill=party)) +geom_col() +
  labs(title ="Wisconsin's Presidential Popular Vote Share",
       subtitle = "1980-2016",
    x="Election Year",y= "Vote Share(%)") +
  theme(plot.title = element_text(face = "bold",size=22)) +
    scale_fill_manual(labels=c("Democrat", "Republican"), values = c("blue", "red")) +
    labs(fill = "Party") +
  theme(legend.title = element_text(color = "gray1", size = 25),legend.key.width = unit(1.4,"cm"),legend.key.size = unit(1.4, "cm")) +
    theme(
  legend.text = element_text(color = "black", size = 17)
  )+
    theme(axis.text.x = element_text(color = "black", size = 27, hjust = .5, vjust = .5, face = "plain"),
        axis.text.y = element_text(color = "black", size = 27, angle = 0, hjust = 1, vjust = 0, face = "plain"))+
  theme(
  axis.title.x = element_text(size = 28),
  axis.title.y = element_text(size = 28))+
  theme(plot.subtitle = element_text(face = "bold",size=21))


plot_grid(Arizona,Florida,Georgia)

ggsave("PV_southern_states_historical.png", height = 12, width = 18)

plot_grid(Minnesota,Wisconsin,Michigan)

ggsave("PV_midwest_states_historical.png", height = 12, width = 18)

plot_grid(Pennsylvania,North_Carolina)

ggsave("PV_coast_states_historical.png", height = 12, width = 18)



  
  
```

```{r}
## shapefile of states from `maps` library
states_map <- map_data("state")
unique(states_map$region)

## read/clean/merge state pop vote


popvote_bystander$region <- tolower(popvote_bystander$state)

pv_map <- popvote_bystander %>%
    filter(year == 2016) %>%
    left_join(states_map, by = "region")


## map: win-margins
pv_margins_map <- popvote_bystander %>%
    filter(year == 2016) %>%
    left_join(states_map, by = "region") %>%
    mutate(win_margin = (R_pv2p-D_pv2p))

map <- ggplot(pv_margins_map, aes(long, lat, group = group)) +
    geom_polygon(aes(fill = win_margin), color = "black") +
    scale_fill_gradient2(
      high = "red2", 
      mid = "white",
      name = "win margin",
      low = "dodgerblue2", 
      breaks = c(-50,-25,0,25,50), 
      limits=c(-52,52)
    ) +
    theme_void()  

# Adding state abbreivations 

centroids <- data.frame(region=tolower(state.name), long=state.center$x, lat=state.center$y)
centroids$abb<-state.abb[match(centroids$region,tolower(state.name))]


x_boundary = -77
x_limits <- c(-50, NA)

map2 <- map  +
  # if need to repel labels... could further finetune
  
  geom_label(data = centroids,
                   aes(x = long,y = lat, label = abb),
    force = 5, hjust = 1, size = 11,
   inherit.aes = F
  ) +

  
  # add titles
  
  labs(fill ="Win Margin") +
  labs(title ="2016 Popular Vote Win Margins by State",caption = "Source:Popular Vote Share by State 1948-2016 Dataset")+
  ggtitle("2016 Popular Vote Win Margins by State") +
  theme(plot.title = element_text(face = "bold",size=38)) +
  theme(plot.caption =element_text(face = "bold",size=32)) +
  theme(legend.title = element_text(color = "gray1", size = 29),legend.key.width = unit(1.9,"cm"),legend.key.size = unit(1.9, "cm")) + theme(legend.text=element_text(size=24)) 
  


ggsave("Intro_Map.png", height = 16, width = 21)


```


